#!/usr/bin/env python3
"""
Delete the REGENERABLE pipeline outputs (previous run's products) to free space.

WHITELIST (only these are deleted), for E1 and E2:
    data/02_Pipeline_Output_<EXP>/Method_Regression
    data/02_Pipeline_Output_<EXP>/Method_Standard
    data/02_Pipeline_Output_<EXP>/Baseline_Raw

NEVER TOUCHED:
    data/02_Pipeline_Output_<EXP>/Covariates   (manual, irreplaceable SVO xlsx)
    data/00_Raw_Input, data/_archive_*, anything else

These folders are fully regenerated by re-running the pipeline.

USAGE (from project root):
    python cleanup_pipeline_outputs.py --dry-run   # preview, deletes nothing
    python cleanup_pipeline_outputs.py             # actually delete
"""

import os
import shutil
import sys

EXPERIMENTS = ["E1", "E2"]
REGENERABLE = ["Method_Regression", "Method_Standard", "Baseline_Raw"]
PROTECTED = "Covariates"


def size_mb(path):
    total = 0
    for root, _dirs, files in os.walk(path):
        for f in files:
            try:
                total += os.path.getsize(os.path.join(root, f))
            except OSError:
                pass
    return round(total / (1024 * 1024), 1)


def main():
    dry = "--dry-run" in sys.argv[1:]
    root = os.path.dirname(os.path.abspath(__file__))
    freed = 0.0
    print(("DRY-RUN (nothing will be deleted)\n" if dry else "") + "")
    for exp in EXPERIMENTS:
        base = os.path.join(root, "data", f"02_Pipeline_Output_{exp}")
        if not os.path.isdir(base):
            print(f"[skip] {base} (not found)")
            continue
        for sub in REGENERABLE:
            target = os.path.join(base, sub)
            if not os.path.isdir(target):
                print(f"[skip] {os.path.relpath(target, root)} (not present)")
                continue
            mb = size_mb(target)
            freed += mb
            print(f"[{'WOULD DELETE' if dry else 'DELETE'}] {os.path.relpath(target, root)}  ({mb} MB)")
            if not dry:
                shutil.rmtree(target)
        # Reassure: confirm the irreplaceable manual folder is still there.
        cov = os.path.join(base, PROTECTED)
        status = "present (UNTOUCHED)" if os.path.isdir(cov) else "NOT FOUND (!)"
        print(f"       Covariates for {exp}: {status}")

    print(f"\n{'Would free' if dry else 'Freed'} ~{freed/1024:.1f} GB.")
    if dry:
        print("This was a DRY RUN. Re-run without --dry-run to actually delete.")


if __name__ == "__main__":
    main()
